In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [13]:
sx = np.array([[0,1], [1,0]])
eigenvector_sx = np.linalg.eig(sx)

a = 0+1j
sy = np.array([[0,-a], [a,0]])
eigenvector_sy = np.linalg.eig(sy)

sz = np.array([[1,0], [0,-1]])
eigenvector_sz = np.linalg.eig(sz)

eigenvector_sx, eigenvector_sy, eigenvector_sz

((array([ 1., -1.]),
  array([[ 0.70710678, -0.70710678],
         [ 0.70710678,  0.70710678]])),
 (array([ 1.+0.j, -1.+0.j]),
  array([[-0.        -0.70710678j,  0.70710678+0.j        ],
         [ 0.70710678+0.j        ,  0.        -0.70710678j]])),
 (array([ 1., -1.]),
  array([[1., 0.],
         [0., 1.]])))

In [22]:
A = np.array([[2,-1],[-1,2]])
eigenvector_A = np.linalg.eig(A)

eigenvector_A

(array([3., 1.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

In [ ]:
([[2,-1],[-1,2]])의 eigenvalue를 구하면 lambda = 3, 1이 나오게 된다. 
이러한 eigenvalue값을 대입하여 eigenvector를 구하게 되면 
lambda가 3일 때 v1 = ([1,-1]), 
lambda가 1일 때 v2 = ([1,1])가 나온다.
v1은 같은 크기로 운동하지만 방향이 반대이고
v2는 같은 크기로 운동하고 방향도 같다.
eigenvector는 두 물체의 운동의 크기의 비와 운동하는 방향을 나타낸다.